FROM alpine:3.19

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai

RUN apk add --no-cache ca-certificates tzdata su-exec && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /app

COPY build/docker/${TARGETPLATFORM}/octopus /app/octopus
COPY scripts/dockerfiles/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh /app/octopus

CMD ["/entrypoint.sh"]